# Generated by Django 3.0.2 on 2020-02-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('img1', models.FileField(blank=True, upload_to='')),
                ('img2', models.FileField(blank=True, upload_to='')),
                ('img3', models.FileField(blank=True, upload_to='')),
                ('img4', models.FileField(blank=True, upload_to='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.items')),
            ],
        ),
    ]
