# Generated by Django 3.0.2 on 2020-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(),
        ),
    ]
