# Generated by Django 3.0.2 on 2020-02-06 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0003_auto_20200205_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_type', models.CharField(max_length=70)),
                ('Numberofguests', models.IntegerField()),
                ('Numberofrooms', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('BookedDate', models.DateField()),
                ('BookedFor', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
