# Generated by Django 3.0.2 on 2020-02-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='Hotels',
        ),
    ]
